//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rival_Table
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string ProductsName { get; set; }
        public System.DateTime SellDate { get; set; }
        public Nullable<int> SellValue { get; set; }
        public Nullable<int> SellPrice { get; set; }
    }
}
